### ISSUE TITLE
Bug: failing to get product thumbnail image in email templates

### ISSUE THREAD

**Issue by guilherme1805** [saleor/saleor#10692]
### What are you trying to achieve?

Trying to send an order email that includes a product thumbnail.

This behaviour was introduced in the commit 5d1a36b9aaf408016957db04f86397b2e53c2500

### Steps to reproduce the problem

Use an email template with the helper `get_product_image_thumbnail` that is supposed to return an URL to the requested size of image. [Saleor Documentation](https://docs.saleor.io/docs/3.x/developer/available-plugins/user-emails#get_product_image_thumbnail)

Failing usage example:

```
{{get_product_image_thumbnail 60 product.first_image}}
```

### What did you expect to happen?

I expected to get the a product image thumbnail url, something like this `https://example-bucket.s3.amazonaws.com/thumbnails/products/saleor-white-plimsolls-1_ahEvKrm_thumbnail_256.png`

### Logs

```
2022-09-20 17:13:33,220 ERROR celery.app.trace Task saleor.plugins.user_email.tasks.send_fulfillment_update_email_task[bf463304-480b-48a1-83f1-828ef16a8c7a] raised unexpected: AttributeError("'dict' object has no attribute 'name'") [PID:26:MainThread]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/saleor/plugins/user_email/tasks.py", line 224, in send_fulfillment_update_email_task
    send_email(
  File "/app/saleor/plugins/email_common.py", line 227, in send_email
    message = template(context, helpers=helpers)
  File "_templates/_template_1.py", line 131, in render
  File "/usr/local/lib/python3.9/site-packages/pybars/_compiler.py", line 398, in _each
    result.grow(options['fn'](scope))
  File "_templates/_template_1.py", line 55, in block_3
  File "/app/saleor/plugins/email_common.py", line 155, in get_product_image_thumbnail
    thumbnail_file_name = prepare_thumbnail_file_name(image.name, size, None)
AttributeError: 'dict' object has no attribute 'name'
```

`AttributeError: 'dict' object has no attribute 'name'"` where dict (`image`) is:
```python
{
   "original":{
      "32":"/thumbnail/UHJvZHVjdE1lZGlhOjI=/32/",
      "64":"/thumbnail/UHJvZHVjdE1lZGlhOjI=/64/",
      "128":"/thumbnail/UHJvZHVjdE1lZGlhOjI=/128/",
      "256":"https://example-bucket.s3.amazonaws.com/thumbnails/products/saleor-white-plimsolls-1_ahEvKrm_thumbnail_256.png",
      "512":"/thumbnail/UHJvZHVjdE1lZGlhOjI=/512/",
      "1024":"/thumbnail/UHJvZHVjdE1lZGlhOjI=/1024/",
      "2048":"/thumbnail/UHJvZHVjdE1lZGlhOjI=/2048/",
      "4096":"/thumbnail/UHJvZHVjdE1lZGlhOjI=/4096/"
   }
}
```

Affecting code:

https://github.com/saleor/saleor/blob/a5c3dd97b5c81bb8121617ed019971fb96ab8172/saleor/plugins/email_common.py#L152-L162

### Environment

Saleor version: 3.7.4

**Comment by peelar** [comment]
Hello @guilherme1805 👋 

Thanks for your effort in describing the issue. We added it to our backlog and will let you know once it's fixed. Have a nice day!

**Comment by aniav** [comment]
This issue has been addressed and is not present in Saleor 3.20 🙌

**Comment by guilherme1805** [comment]
Thank you 🙌
